# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  authserver:
    image: authserver
    build:
      context: .
      dockerfile: backend/src/AuthServer/Dockerfile
    ports:
      - 5269:5269
