CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE auth_users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    email character varying(50) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_auth_users" PRIMARY KEY (user_id)
);

CREATE TABLE auth_sessions (
    session_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token character varying(100),
    user_agent character varying(255),
    ip_address character varying(45),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_auth_sessions" PRIMARY KEY (session_id),
    CONSTRAINT "FK_auth_sessions_auth_users_user_id" FOREIGN KEY (user_id) REFERENCES auth_users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_profiles (
    profile_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    birth_date timestamp with time zone,
    gender character varying(20),
    phone_number character varying(20),
    address character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_profiles" PRIMARY KEY (profile_id),
    CONSTRAINT "FK_user_profiles_auth_users_user_id" FOREIGN KEY (user_id) REFERENCES auth_users (user_id) ON DELETE CASCADE
);

CREATE INDEX "IX_auth_sessions_token" ON auth_sessions (token);

CREATE INDEX "IX_auth_sessions_user_id" ON auth_sessions (user_id);

CREATE UNIQUE INDEX "IX_auth_users_email" ON auth_users (email);

CREATE UNIQUE INDEX "IX_user_profiles_user_id" ON user_profiles (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250430160825_AuthServerInit', '8.0.15');

COMMIT;

