# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**' 
  workflow_dispatch:
    inputs:
      build_binary:
        description: 'Build AOT binary'
        required: false
        type: boolean
        default: false
      build_image:
        description: 'Build Docker image'
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
  
  build-aot:
    name: AOT Compilation
    needs: test
    # Run only on PR to main or when manually triggered with build_binary option
    if: (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch' && inputs.build_binary)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: AOT Compilation
      run: dotnet publish --configuration Release -p:PublishAot=true --self-contained true -o ./publish
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aot-build
        path: ./publish/
        retention-days: 7

  build-docker:
    name: Build Docker Image
    needs: build-aot
    # Run only on PR to main or when manually triggered with build_image option
    if: (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch' && inputs.build_image)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: aot-build
        path: ..//publish/
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request' # Only login for pushes, not PRs
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: your-organization/your-app-name
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha,format=short
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }} # Only push on non-PR events
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
